project:
  type: website
  output-dir: docs

website:
  title: "Mateus Maia"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: cv/mateusmaia_cv.pdf
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

