project:
  type: website

website:
  title: "Mateus Maia"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: index.qmd
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

