project:
  type: website
  output-dir: _site
  

website:
  title: "Mateus Maia"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: software.qmd
        text: Software
      - href: mateusmaia_cv.pdf
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

