---
title: "Research "
editor: visual
format: 
  html: 
    fontsize: 95%
---

### Research Interests

::: justify
My research interests span a broad spectrum within the field of statistics, encompassing statistical machine learning, Bayesian statistics, and ensemble methods. Over the years, I have been actively involved in the development of statistical models tailored for predictive tasks. Specifically, my focus lies in extending Bayesian Additive Regression Trees models (BART) to address various situations where model assumptions may not always hold true or can be expanded. Additionally, I am intrigued by the development of models based on Support Vector Machines (SVM), where I explore ways to adapt them to ensemble approaches and investigate the impact and influence of novel kernel functions. My applied statistics focus is diverse, ranging from demographic data to image and signal processing, all with the overarching goal of achieving predictive outcomes.
:::

## List of Publications

::: justify
### 2023

-   **Maia, Mateus,** Keefe Murphy, and Andrew C. Parnell. [GP-BART: a novel Bayesian additive regression trees approach using Gaussian processes.](https://www.sciencedirect.com/science/article/pii/S016794732300169X#:~:text=The%20Gaussian%20processes%20Bayesian%20additive,terminal%20node%20among%20all%20trees.) Computational Statistics & Data Analysis (2023): 107858.

-   **Maia, Mateus**, *et. al*. . [Wavelet Support Vector Censored Regression](https://doi.org/10.3390/analytics2020023). Analytics 2.2 (2023): 410-425.

### 2022

-   Ara, A., **Maia, M.**, Louzada, F., Macêdo, S. Regression random machines: [An ensemble support vector regression model with free kernel choice](https://doi.org/10.1016/j.eswa.2022.117107). Expert Systems with Applications 202 (2022): 117107.

### 2021

-   **Maia, Mateus**, Arthur R. Azevedo, and Anderson Ara. [Predictive comparison between random machines and random forests.](https://doi.org/10.6339/21-JDS1025) Journal of Data Science 19.4 (2021): 593-614.

-   Ara, A., **Maia, M**., Louzada, F., & Macêdo, S. [Random machines: A bagged-weighted support vector model with free kernel choice](https://doi.org/10.6339/21-JDS1025). Journal of Data Science 19.3 (2021): 409-428.

### 2020

-   **Maia, Mateus**, *et al*. [Convolutional support vector models: Prediction of coronavirus disease using chest x-rays](https://doi.org/10.3390/info11120548). Information 11.12 (2020): 548.

-   Paz, H., **Maia, M.**, Moraes, F., Lustosa, R., Costa, L., Macêdo, S., & Ara, A. [Local processing of massive databases with R: a national analysis of a Brazilian social programme](https://doi.org/10.3390/stats3040028). Stats 3.4 (2020): 444-464.
:::

## Selected Presentations

-   **Oral presentation:** Mateus Maia**,** Keefe Murphy, and Andrew C. Parnell. [sBART: novel extension to Bayesian additive regression trees using splines](/presentations/casi_2023_correct_version_mateus_maia.pdf). Conference of Applied Statistics in Ireland (CASI) 2023 , Killaerney, Ireland.

-   **Poster presentation**: Mateus Maia, Keefe Murphy, and Andrew C. Parnell. 2023. [GP-BART: an extension to Bayesian additive regression trees approach using Gaussian processes](presentations/poster_bayescomp_v6). BayesComp, 2023 . Kittila, Finland.

-   **Oral presentation:** Mateus Maia, [2nd place at the Best Master Thesis Competition : "Random Machines - The Random Kernel Space for Constructing a Support Vector Ensemble"](presentation/sinape_contest). 24th SINAPE \| National Symposium on Probability and Statistics of Brazil organised by the Brazilian Association of Statistics. 2022. (PT-BR version).

-   **Oral presentation**: Mateus Maia, Keefe Murphy, and Andrew C. Parnell. [A new Extension For Bayesian Additive Regression Trees Model Adopting Gaussian Processes](presentations/casi_slides2022). Conference of Applied Statistics in Ireland (CASI) 2022, Cork, Ireland.
