---
editor: visual
---

# R packages

## $\texttt{randomMachines::}$ {.justify style=".justify"}

This R package is available on [CRAN](https://cran.r-project.org/web/) as $\texttt{randomMachines}$ package, which implements a novel ensemble method employing Support Vector Machines (SVMs) as base learners. This powerful ensemble model is designed for both classification (Ara A., et. al, 2021) \<[doi:10.6339/21-JDS1014](https://doi.org/10.6339%2F21-JDS1014)\>, and regression (Ara A., et. al, 2021) \<[doi:10.1016/j.eswa.2022.117107](https://doi.org/10.1016%2Fj.eswa.2022.117107)\> problems, offering versatility and robust performance across different datasets and compared with other consolidated methods as Random Forests (Maia M, et. al, 2021) \<[doi:10.6339/21-JDS1025](https://doi.org/10.6339%2F21-JDS1025)\>.

To install it only need to run

``` r
install.packages(randomMachines)
```

## $\texttt{gpbart::}$

A R implementation built on $\texttt{C++}$ and $\texttt{Rcpp}$ of the extension of Bayesian Additive Regression Trees using Gaussian Processes developed by myself, Keefe Murphy and Andrew Parnell. More details of the statistical model are presented in the paper entitled: "GP-BART: A novel Bayesian additive regression trees approach using Gaussian processes" publisehd at the Computational & Data Analysis journal.

The repository can be found at: https://github.com/MateusMaiaDS/gpbart, and to install it only need to run:

``` r
devtools::install_github("MateusMaiaDS/gpbart")
```
